### ISSUE TITLE
Keyboard Shortcuts: How exactly ;)

### ISSUE THREAD

**Issue by GuitarTab** [ijgnd/anki__quick_note_and_deck_change_menus#1]
> You can assign the menu entries hotkeys by prepending "&" in front of a letter.

I tried that; it's slightly above my head ...

I don't need any menus (I could just use Anki's dropdown menus), instead, "Ctrl+1" should select Basic (for example), and "Ctrl+2" should select Cloze.

Where and how exactly would I have to insert Ctrl+1/2 ?

Maybe you could post a short example on the website; b/c keyboard shortcuts (and not menus) is probably why people want to use this addon.

Thanks :D

**Comment by ijgnd** [comment]
> "Ctrl+1" should select Basic (for example), and "Ctrl+2" should select Cloze.

This add-on was not designed for this. Instead use the add-on [Quick note and deck buttons (Fork for 2.1)](https://ankiweb.net/shared/info/1331140127).

**Comment by GuitarTab** [comment]
Thanks for replying, appreciated!
